---
title: "1.3 — Sequential Games I — Class Content"
draft: false
linktitle: "1.3 — Sequential Games"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "1.3-slides"
---

{{% alert note %}}
*Monday August 30, 2021* & *Wednesday September 1, 2021*
{{% /alert %}}

{{% alert warning %}}
Problem Set 1 (to be posted today) is due Wednesday September 8. 
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we begin looking at sequential games.

Don't forget to register and account and join our course on [Moblab](https://moblab.com)!

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`