---
title: "1.5 — Coordination Games & Multiple Equilibria — Class Content"
draft: false
linktitle: "1.5 — Coordination Games & Multiple Equilibria"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "1.5-slides"
---

{{% alert note %}}
*Monday September 13, 2021*
{{% /alert %}}

{{% alert warning %}}
[Problem Set 2](/assignments/02-problem-set) is due Wednesday September 22. 
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we begin looking at simultaneous games.

## <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fa-book"></i> Ch. 4 in Dixit and Nalebuff (paperback)
- <i class="fas fa-book"></i> Chs. 4.6, 5.3 in Dixit, Skeath, and Riley (textbook)

## Optional/Referenced Readings

- <i class="fas fa-book"></i> Schelling, Thomas, 1960, [*The Strategy of Conflict*](/readings/Schelling-1960-Ch3.pdf) (Ch.3 excerpt)
- <i class="fas fa-file-pdf"></i> David, Paul A, 1985, ["Clio and the Economics of QWERTY"](/readings/David-1985.pdf), *American Economic Review* 
- <i class="fas fa-file-pdf"></i> Liebowitz, Stan J and Stephen E Margolis, 1990, ["The Fable of the Keys"](/readings/Leibowitz-Margolis-1990.pdf), *Journal of Law and Economics*
- <i class="fas fa-file-pdf"></i> Arthur, W. Brian, 1989, ["Competing Technologies, Increasing Returns, and Lock-In by Historical Events"](/readings/Arthur-1989.pdf), *Economic Journal*

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`