---
title: "2.4 — Stackelberg Competition — Class Content"
draft: false
linktitle: "2.4 — Stackelberg Competition"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "2.4-slides"
---

{{% alert note %}}
*Monday September 27, 2021*.
{{% /alert %}}

{{% alert warning %}}
[Problem Set 3](/assignments/03-problem-set) is due on Wednesday October 6. 
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we look at our final major model of oligopoly: Steckelberg competition, where firms compete on quantity *sequentially*.

## <i class="fas fa-book-reader fa-lg"></i> Readings

While the textbook does briefly describe the economics of oligopoly in passing, they do not get into the details, nor do they look at the canonical models that we will study. As such, for today I can only recommend my slides to assist you. 

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`

## Cournot Practice Problems

The slides contain a practice problem of Cournot competition. I have added the answer key:

- [<i class="far fa-life-ring"></i> Answer Key](/assignments/oligopoly_practice_answers.html)

## <i class="fas fa-laptop-code"></i> Assignments

### Problem Set 3 Due Wed Oct 6

[Problem set 3](/assignment/03-problem-set) is by the end of the day Wednesday, October 6.