---
title: "3.2 — Repeated Games — Class Content"
draft: false
linktitle: "3.2 — Repeated Games"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "3.2-slides"
---

{{% alert note %}}
*Wednesday October 20, 2021*.
{{% /alert %}}


## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we look at repeated games.

## <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fa-book"></i> Ch. 3 in Dixit and Nalebuff (paperback)
- <i class="fas fa-book"></i> Chs. 10 in Dixit, Skeath, and Riley (textbook)

## Recommended/Primary Sources

- Axelrod, 1984, *The Evolution of Cooperation*
- [<i class="fas fa-external-link-square-alt"></i> fivethirtyeight: How to Win a Trade War](https://fivethirtyeight.com/features/how-to-win-a-trade-war/)

The fivethirtyeight article contains a simulation based on Axelrod's prisoners' dilemma tournament (though, in the context of international trade/trade wars) where you can choose your strategy and play with a computer (following their own strategy) to see how you fare after 100 rounds.

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`

## <i class="fas fa-laptop-code"></i> Assignments

