---
title: "3.3 — Evolution of Cooperation — Class Content"
draft: false
linktitle: "3.3 — Evolution of Cooperation"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "3.3-slides"
---

{{% alert note %}}
*Monday October 24, 2021*.
{{% /alert %}}


## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we look at repeated games.

## <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fa-book"></i> Ch. 3 in Dixit and Nalebuff (paperback)
- <i class="fas fa-book"></i> Chs. 10 in Dixit, Skeath, and Riley (textbook)

## Recommended/Primary Sources

- Axelrod, 1984, *The Evolution of Cooperation*
- [<i class="fas fa-file-pdf"></i> Klein, Crawford, and Alchian (1972), “Vertical Integration, Appropriable Rents, and the Competitive Contracting Process”](/readings/Klein-Leffler-1981.pdf)
- [<i class="fas fa-file-pdf"></i> Klein and Leffler (1981), “The Role of Market Forces in Assuring Contractual Performance”](/readings/Klein-Leffler-1981.pdf)
- [<i class="fas fa-file-pdf"></i> Milgom, North, and Weingast (1990), "The Role of Institutions in the Revival of Trade: The Law Merchant, Private Judges, and the Champagne Fairs"](/readings/Milgrom-North-Weingast-1990.pdf)
- [<i class="fas fa-file-pdf"></i> Benson (1989), "The Spontaneous Evolution of Commercial Law"](/readings/Benson-1989.pdf)

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`

## <i class="fas fa-laptop-code"></i> Assignments

