---
title: "3.4 — Evolutionarily Stable Strategies — Class Content"
draft: false
linktitle: "3.4 — Evolutionarily Stable Strategies"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "3.4-slides"
---

{{% alert note %}}
*Wednesday October 27, 2021*.
{{% /alert %}}


## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we look at evolutionary games.

## <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fa-book"></i> Ch. 9 in Dixit and Nalebuff (paperback)
- <i class="fas fa-book"></i> Chs. 11 in Dixit, Skeath, and Riley (textbook)

## Recommended/Primary Sources

- [<i class="fas fa-book"></i> Maynard Smith, 1982, *Evolution and the Theory of Games*, Ch. 2: “The Basic Model”](/readings/maynard-smith-1982-Ch2.pdf)

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`