---
title: "4.2 — Credible Commitments — Class Content"
draft: false
linktitle: "4.2 — Credible Commitments"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "4.2-slides"
---

{{% alert note %}}
*Monday November 8, 2021*.
{{% /alert %}}


## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we begin looking at how players can make promises and threats that are credible, by committing themselves to carrying out that action.

## <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fa-book"></i> Chs. 9 in Dixit, Skeath, and Riley (textbook)
- [<i class="fas fa-file-pdf"></i> Brining (1990), "Rings and Promises"](/readings/Brining-1990.pdf)

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`