---
title: "4.3 — Political Economy of Credible Commitments — Class Content"
draft: false
linktitle: "4.3 — Political Economy of Credible Commitments"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "4.3-slides"
---

{{% alert note %}}
*Wednesday November 19, 2021*.
{{% /alert %}}


## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we discuss several examples of the credible commitment problem in political economy.

## <i class="fas fa-book-reader fa-lg"></i> Readings

- <i class="fas fa-book"></i> Chs. 9 in Dixit, Skeath, and Riley (textbook)
- [<i class="fas fa-file-pdf"></i> Greif, Milgrom, and Weingast (1994), "Coordination, Commitment, and Enforcement: The Case of the Merchant Guild"](/readings/Greif-Milgrom-Weingast-1994.pdf)
- [<i class="fas fa-file-pdf"></i> Weingast (1995), "The Economic Role of Political Institutions: Market-Preserving Federalism and Economic Development"](/readings/Weingast-1995.pdf)
- [<i class="fas fa-file-pdf"></i> Fearon (1995), "Rationalist Explanations for War"](/readings/Fearon-1995.pdf)
- [<i class="fas fa-file-pdf"></i> Allison (2015), "The Thucydides Trap: Are the U.S. and China Headed for War?", *The Atlantic*](https://www.theatlantic.com/international/archive/2015/09/united-states-china-war-thucydides-trap/406756)

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`