---
title: "4.7 — Preference Falsification & Information Cascades — Class Content"
draft: false
linktitle: "4.7 — Preference Falsification & Information Cascades"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "4.7-slides"
---

{{% alert note %}}
*Monday November 22, 2021*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Related to signaling — where an informed player wishes to signal their type to an uninformed player — we consider another phenomenon that can be very useful idea to explain politics, revolutions, surprises, and public opinion: preference falsification. Individuals have true beliefs or preferences, but may display a different, deliberately false, set of preferences in public for a variety of reasons. Critical events can also rapidly and dramatically shift people's preferences that they project to the public (most dramatically in the form of spontaneous revolutions) when it is made plain to everyone how false the public preferences are.

## <i class="fas fa-book-reader fa-lg"></i> Readings

- [<i class="fas fas fa-book"></i> Kuran (1997), *Private Truths, Public Lies: The Social Consequences of Preference Falsification*, Ch. 1](/readings/Kuran-1997-Ch1.pdf)

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`