---
title: "Problem Set 3"
draft: false
linktitle: "Problem Set 3"
date: "2020-06-08"
menu:
  assignments:
    parent: Problem Sets
    weight: 4
type: docs
---

{{% alert note %}}
Due on *Wednesday October 6*.
{{% /alert %}}

<p style="text-align:center"><a target="_blank" href="/assignments/02-problem-set-pdf.pdf"><span class="btn btn-primary btn-lg"><i class="fas fa-file-pdf"></i> Download PDF</a></span></p>

Please read the [instructions](/assignments/problem-sets) for completing homeworks.

# Concepts

## Question 1

Explain what cartels are, the problems that they face, and some methods by which these problems might be overcome.   

## Question 2

Describe the major differences between Bertrand competition, Cournot competition, and Stackelberg competition. How do firms compete, and what are the results in terms of market price, industry output, and profits for firms? 

## Question 3

Describe the conditions required to make a market *contestable*. Describe and compare the Nash equilibrium of a contestable market with a pure monopoly, and with perfect competition.    

# Problems

## Question 4

Suppose Comcast $(C)$ and Verizon $(V)$ have a constant $MC=AC=\$20$ per customer connected to their internet network. The market (inverse) demand curve for basic internet service is given by:
$$\begin{align*}
P&=80-2Q\\
Q&=q_C+q_V\\
\end{align*}$$

### Part A

Find the Cournot-Nash equilibrium output, price, and profit for each firm.

### Part B

Find the output, price, and profit for each firm if the two were to collude.

### Part C

Suppose now Comcast is a Stackelberg leader. Find each firm's output, price, and profit.

### Part D

Find the output, price, and profit for each firm they were to compete on *price* instead of *quantity.*

## Question 5

This question will show what happens as we relax some of the assumptions of Cournot competition. Crude oil is transported across the globe in enormous tanker ships called Very Large Crude Carriers (VLCCs). By 2001, more than 92% of all new VLCCs were built in South Korea and Japan. Assume that the price of new VLCCs (in millions of dollars) is determined by the inverse demand function between the duopoly of Korea and Japan: 

$$\begin{align*}p&=180-Q\\
Q&=q_{Korea}+q_{Japan}\\
\end{align*}$$

Assume the marginal cost of building each ship is <span>&#36;</span>30 (million) in both Korea and Japan.

### Part A

Find each country's best response function, the Nash equilibrium quantity produced by each country, the market price, and the profit for each country.

### Part B

Labor costs in Korean shipyards are actually lower than in Japan. Assume now the marginal cost per ship in Japan is <span>&#36;</span>40 (million) and only <span>&#36;</span>20 (million) in Korea. Find the new best response functions, the Nash equilibrium quantity produced by each country, the market price, and the profit for each country.

### Part C

Suppose China decides to enter the VLCC construction market. The duopoly now becomes a triopoly, so that the market inverse demand function is:

$$\begin{align*}
p&=180-Q\\
Q&=q_{Korea}+q_{Japan}+q_{China}\\
\end{align*}$$

Assume for simplicity that all countries face the same marginal cost of <span>&#36;</span>30 (million) per ship. Find the new best response functions, the Nash equilibrium quantity produced by each country, the market price, and the profit for each country. Hint: proceed as before, such that you get three reaction functions with three unknowns.

### Part D

Compare the quantity, price, and profits between parts A, B, and C