---
title: "Term Paper"
draft: false
linktitle: "Term Paper"
date: "2020-06-08"
menu:
  assignments:
    parent: Papers
    weight: 1
type: docs
---

{{% alert note %}}
Due by email on Monday December 6, 2021
{{% /alert %}}

Your task is to write a paper on a topic of your choosing, so long as you apply some game theoretic thinking to it. 

This assignment has several purposes. First, it is my way of gauging whether you understand the material and are attempting to grapple with the challenges it brings to understanding economics. You are perfectly free to accept it, reject it, or find a way to synthesize it with your current understanding of economic issues and research, so long as you argue why!  Second, it is a chance for you to stimulate and develop your own thinking on some of the issues raised in this course, as well as an opportunity to develop your writing and communication skills. These skills are vital to any profession, and in truth, you do not fully understand an idea unless you engage it in writing. Finally, this assignment will be good preparation for your research paper (you could even reuse a topic with appropriate changes).

I am *NOT* looking for a survey of existing research, a series of block quotes showing what economists have said about $x$, a regurgitation of my lectures, a list of pros and cons with a last minute conclusion, a book review, and so on. I also do *NOT* want you to compress *everything* you have learned so far into a single paper. You should only use those insights that you believe are relevant to your topic and your argument. 

I am looking for a paper that is your own take on a topic, and one that puts forth an *argument* and defends it. 

# Length, References, & Mechanics

The required mechanics of this assignment are quite informal. This is not a research paper, nor an op-ed. Imagine it like a conversation among friends about some topic -- it should be reasonably informative and persuasive, but not necessarily a formal piece of writing. I expect you to around **between 7 $\pm$ 3 pages (double spaced, size 12 Times New Roman or Arial font, 1" margins)**.

I would also like you to use scholarly references, that is, articles from economics journals and cite them properly. I do not have a minimum requirement of the amount of references, but I expect you to have at least **2-5 scholarly references**, depending on your paper topic and thesis. I am not particularly picky about exactly how you format your citations or bibliography, just please be consistent, and do not use footnotes or endnotes (only because they annoy me). I *suggest* the APA author-year-page in-text citation format that is fairly standard in economics journals, i.e.: "The division of labor is limited by the extent of the market," (Smith 1776: 27). Look at my slides or my handouts for a suggested bibliography style. If you use `.bib` files, the default formatting is fine. 

# Grading Rubric

Here is the rubric that I will use to grade your paper:


| Category | Points |
|----------|-------:|
| Persuasiveness | 30 |
| Soundness | 30 |
| Clarity | 20 |
| Organization | 10 |
| References | 5 |
| Style | 5 |
| TOTAL | 100 |

- **Economic Soundness**: Does your topic have economic content? Do you properly use economic theory, are your explanations consistent and logical, and did you apply them correctly? Did you choose relevant (and non-cherry picked) evidence to back it up? Are your facts, data, or case studies accurate (if appropriate)? 
- **Persuasiveness:** How persuasive is your argument? Would a reasonably educated college-level reader who is familiar with economics but not necessarily this course find themselves understanding your argument and agreeing with you? [Write for an audience wider than just members of this class. Therefore, don’t use terms, sources, or “inside jokes” that only other students in this class (and no one else) would understand.] Remember, your goal is not to convince me (though you may), your goal is to convince someone else, and I grade you the probability that this is likely. You are the lawyer, I am the judge, and your audience is the jury.
- **Clarity:** How clear is your paper? Is it clear what your thesis is and is it declared early on? Can you summarize the thesis in a sentence? Are there confusing passages, excessive jargon or passive voice, or irrelevant arguments and examples?
- **References:** Does your paper use multiple scholarly references? Does it properly cite them in the text for main ideas borrowed and for direct quotations? Are they consistently listed at the end in a references section?
- **Style:** Is your paper interesting and easy to read? Does it engage the reader? Is it written in active voice? This is somewhat subjective, and hence, the smallest portion of your grade
